[package]
name = "aws-devcontainer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs-docker = "0.0.60"
structopt = "0.3"
serde = { version="1.0", features=["derive"] }
serde_json = "1.0"