[package]
name = "jwt-jwk-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonwebtoken = "7.2.0"
serde = {version = "1.0.130", features = ["derive"] }
serde_json = "1.0.74"
