FROM ubuntu:20.04


RUN apt-get update \
 # TODO: Remove upgrade statements once packages are updated in base image
 && apt-get -y upgrade --only-upgrade systemd openssl \
 && apt-get install -y --no-install-recommends \
    ca-certificates \
    build-essential \
    nano \
    wget \
    curl \
    git \
    libssl-dev \
    libffi-dev \
    python3-dev \
    python3-pip \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*


# Get Rust
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y

RUN echo 'source $HOME/.cargo/env' >> $HOME/.bashrc

RUN pip3 install transformers torch

WORKDIR /code